### PR TITLE
Performance audit

### PR DESCRIPTION
**Pull request by j-tee**
## In this Milestone:
- Add emails column to owners table
- Add data more data to the database
- Analyse queries
- Create non clustered index to reduce execution time
### Screenshots

image
image (1)
image (2)

### CODE REVIEW

**Review by danmainah — CHANGES_REQUESTED** [review]
Hi @j-tee and @Baayeh , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Gitfow was correctly used
✔️  Good design


# Required Changes ♻️

- [x] @team great work on your queries, however, the second query doesn't show the use of indexes as in the other screenshot, making the query difference small, kindly consider adding the adding index query before the second query as you did in the other queries.

- [x] Also in the final query (email query) the initial execution time is below 1000ms, kindly run populate database query a few more times until the execution time is above 1000ms.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Baayeh** [comment]
- Analyzed the `SELECT * FROM owners where email = 'owner_18327@mail.com';` query again

image

**Comment by Baayeh** [comment]
- Created the index for the `vet_id` and analyzed the query `SELECT * FROM visits where vet_id = 2;` again.

image

**Review by Nemwel-Boniface — APPROVED** [review]
## Hello @j-tee  and @Baayeh        :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 



## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
